import { InstrumentParams, InstrumentType, Step } from '../types';

let _id = 0;
const uid = () => `inst_${++_id}`;

export function makeStep(overrides?: Partial<Step>): Step {
  return { active: false, velocity: 0.9, accent: false, note: 0, ...overrides };
}

function base(
  overrides: Partial<InstrumentParams> & { name: string; type: InstrumentType; color: string }
): InstrumentParams {
  return {
    id: uid(),
    wave: 'square',
    pulseWidth: 0.5,
    frequency: 440,
    freqEnd: 440,
    attack: 0.001,
    decay: 0.15,
    sustain: 0,
    release: 0.05,
    pitchSweepTime: 0.1,
    filterType: 'lowpass',
    filterFreq: 8000,
    filterQ: 1,
    filterEnvAmt: 0,
    bitCrush: 16,
    distortion: 0,
    reverbMix: 0,
    delayMix: 0,
    delayTime: 0.25,
    delayFeedback: 0.3,
    volume: 0.8,
    pan: 0,
    arpNotes: [],
    arpSpeed: 0.05,
    vibratoRate: 0,
    vibratoDepth: 0,
    tremoloRate: 0,
    tremoloDepth: 0,
    muted: false,
    ...overrides,
  };
}

export const DEFAULT_INSTRUMENTS: InstrumentParams[] = [
  base({
    id: 'kick',
    name: 'KICK',
    type: 'kick',
    color: '#ef4444',
    wave: 'sine',
    frequency: 180,
    freqEnd: 38,
    pitchSweepTime: 0.07,
    attack: 0.001,
    decay: 0.38,
    sustain: 0,
    release: 0.12,
    volume: 0.95,
    filterFreq: 220,
    filterType: 'lowpass',
    filterQ: 0.5,
    bitCrush: 14,
    distortion: 0.08,
  }),
  base({
    id: 'snare',
    name: 'SNARE',
    type: 'snare',
    color: '#f97316',
    wave: 'noise',
    frequency: 200,
    freqEnd: 100,
    attack: 0.001,
    decay: 0.20,
    sustain: 0,
    release: 0.07,
    volume: 0.75,
    filterType: 'bandpass',
    filterFreq: 1800,
    filterQ: 1.5,
    bitCrush: 7,
    distortion: 0.1,
  }),
  base({
    id: 'hihat',
    name: 'HI-HAT',
    type: 'hihat',
    color: '#eab308',
    wave: 'noise',
    frequency: 8000,
    freqEnd: 8000,
    attack: 0.001,
    decay: 0.055,
    sustain: 0,
    release: 0.02,
    volume: 0.5,
    filterType: 'highpass',
    filterFreq: 7500,
    filterQ: 0.8,
    bitCrush: 5,
  }),
  base({
    id: 'openhat',
    name: 'OPEN HAT',
    type: 'openhat',
    color: '#84cc16',
    wave: 'noise',
    frequency: 8000,
    freqEnd: 8000,
    attack: 0.001,
    decay: 0.38,
    sustain: 0.08,
    release: 0.25,
    volume: 0.42,
    filterType: 'highpass',
    filterFreq: 6500,
    filterQ: 0.8,
    bitCrush: 5,
    pan: 0.15,
  }),
  base({
    id: 'clap',
    name: 'CLAP',
    type: 'clap',
    color: '#22c55e',
    wave: 'noise',
    frequency: 1000,
    freqEnd: 1000,
    attack: 0.004,
    decay: 0.14,
    sustain: 0,
    release: 0.09,
    volume: 0.7,
    filterType: 'bandpass',
    filterFreq: 3200,
    filterQ: 2.5,
    bitCrush: 6,
    pan: -0.15,
    reverbMix: 0.12,
  }),
  base({
    id: 'tom',
    name: 'TOM',
    type: 'tom',
    color: '#06b6d4',
    wave: 'triangle',
    frequency: 230,
    freqEnd: 75,
    pitchSweepTime: 0.09,
    attack: 0.001,
    decay: 0.28,
    sustain: 0,
    release: 0.09,
    volume: 0.78,
    filterType: 'lowpass',
    filterFreq: 2200,
    filterQ: 1,
    bitCrush: 11,
  }),
  base({
    id: 'bass',
    name: 'BASS',
    type: 'bass',
    color: '#8b5cf6',
    wave: 'square',
    frequency: 55,
    freqEnd: 55,
    attack: 0.002,
    decay: 0.18,
    sustain: 0.25,
    release: 0.1,
    volume: 0.82,
    filterType: 'lowpass',
    filterFreq: 700,
    filterQ: 3,
    filterEnvAmt: 0.4,
    bitCrush: 10,
    arpNotes: [0, 7, 12, 7],
    arpSpeed: 0.08,
  }),
  base({
    id: 'lead',
    name: 'LEAD',
    type: 'lead',
    color: '#ec4899',
    wave: 'pulse',
    pulseWidth: 0.3,
    frequency: 440,
    freqEnd: 440,
    attack: 0.008,
    decay: 0.12,
    sustain: 0.45,
    release: 0.18,
    volume: 0.58,
    filterType: 'lowpass',
    filterFreq: 3500,
    filterQ: 4,
    bitCrush: 8,
    vibratoRate: 5.5,
    vibratoDepth: 0.25,
    reverbMix: 0.08,
  }),
  base({
    id: 'chord',
    name: 'CHORD',
    type: 'chord',
    color: '#14b8a6',
    wave: 'sawtooth',
    frequency: 220,
    freqEnd: 220,
    attack: 0.06,
    decay: 0.22,
    sustain: 0.55,
    release: 0.35,
    volume: 0.42,
    filterType: 'lowpass',
    filterFreq: 2200,
    filterQ: 1.5,
    bitCrush: 6,
    arpNotes: [0, 4, 7],
    arpSpeed: 0,
    reverbMix: 0.18,
  }),
  base({
    id: 'blip',
    name: 'BLIP',
    type: 'blip',
    color: '#f43f5e',
    wave: 'square',
    frequency: 880,
    freqEnd: 1760,
    pitchSweepTime: 0.035,
    attack: 0.001,
    decay: 0.07,
    sustain: 0,
    release: 0.03,
    volume: 0.58,
    filterType: 'lowpass',
    filterFreq: 5500,
    filterQ: 1,
    bitCrush: 4,
  }),
  base({
    id: 'synth',
    name: 'SYNTH',
    type: 'lead',
    color: '#00d9ff',
    wave: 'sawtooth',
    frequency: 220,
    freqEnd: 220,
    attack: 0.012,
    decay: 0.08,
    sustain: 0.65,
    release: 0.25,
    volume: 0.72,
    filterType: 'lowpass',
    filterFreq: 4200,
    filterQ: 5,
    filterEnvAmt: 0.6,
    bitCrush: 12,
    distortion: 0.04,
    reverbMix: 0.15,
    delayMix: 0.08,
    delayTime: 0.3,
    delayFeedback: 0.4,
    vibratoRate: 6,
    vibratoDepth: 0.2,
    tremoloRate: 0,
    tremoloDepth: 0,
  }),
];

export function defaultPattern(instruments: InstrumentParams[], stepCount = 16) {
  return {
    id: 'pat_1',
    name: 'Pattern 1',
    stepCount,
    swing: 0,
    tracks: instruments.map(inst => ({
      instrumentId: inst.id,
      steps: Array.from({ length: stepCount }, () => makeStep()),
    })),
  };
}
